import { describe, expect, it } from "vitest";
import {
  createChartProvider,
  meanNodeLongitude,
  northNodeLongitude,
  NODE_MODE_LABELS,
  type NodeMode,
} from "@/lib/chart/provider";
import { SIGNS } from "@/lib/types";
import { deltaT } from "@/lib/chart/celestial";
// The gold-master fixtures live outside src; load them by absolute path.
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * INDEPENDENT GOLD-MASTER COMPARISON.
 *
 * The reference values in docs/goldmaster/fixtures.json were generated by the
 * Swiss Ephemeris 2.10.03 (via the swisseph-wasm dev dependency) — the
 * de-facto industry standard used by Astro.com and AstroSeek. They are
 * committed so this test never depends on the GPL WASM module at test time.
 *
 * Tolerances:
 *  - Planet/angle longitudes: 0.10° (arcminute-level agreement).
 *  - Ascendant/MC: 0.10°.
 *  - Placidus cusps: 0.50°.
 *  - Sabian degree and global index: EXACT (no tolerance).
 */

interface GoldPlacement {
  key: string;
  sign: number;
  degree: number;
  minute: number;
  second: number;
  longitude: number;
  signName: string;
  sabian: { sabianDegree: number; globalIndex: number; sign: string };
}

interface GoldFixture {
  id: string;
  label: string;
  utcIso: string;
  lat: number;
  lon: number;
  timeKnown: boolean;
  jd: number;
  placements: GoldPlacement[];
  houses: Record<string, number> | null;
  ascmc: { ascendant: number; mc: number; armc: number } | null;
}

interface GoldMasterFile {
  fixtures: GoldFixture[];
}

const goldmaster: GoldMasterFile = JSON.parse(
  readFileSync(join(process.cwd(), "docs", "goldmaster", "fixtures.json"), "utf8")
);

const SIGNS_TROPICAL = SIGNS as readonly string[];

function degreesEqual(actual: number, expected: number, tolerance: number): void {
  let diff = Math.abs(actual - expected);
  diff = Math.min(diff, 360 - diff);
  expect(diff).toBeLessThanOrEqual(tolerance);
}

function runEngine(fixture: GoldFixture) {
  const provider = createChartProvider();
  const chart = provider.calculate({
    utc: new Date(fixture.utcIso),
    latitude: fixture.lat,
    longitude: fixture.lon,
    timeKnown: fixture.timeKnown,
  });
  return chart;
}

describe("gold-master: planets (Swiss Ephemeris reference)", () => {
  for (const fixture of goldmaster.fixtures) {
    it(`${fixture.id} — Sun through Pluto match SE within 0.10°`, () => {
      const chart = runEngine(fixture);
      const keys = ["sun", "moon", "mercury", "venus", "mars", "jupiter", "saturn", "uranus", "neptune", "pluto"];
      for (const key of keys) {
        const ref = fixture.placements.find((p) => p.key === key)!;
        const actual = chart.placements.find((p) => p.key === key)!;
        degreesEqual(actual.longitude, ref.longitude, 0.1);
        expect(actual.sign).toBe(ref.signName);
        // DMS within the same degree (arcminute agreement).
        expect(Math.abs(actual.degree - ref.degree)).toBeLessThanOrEqual(1);
        expect(Math.abs(actual.minute - ref.minute)).toBeLessThanOrEqual(6);
      }
    });
  }
});

describe("gold-master: North Node (Swiss Ephemeris reference)", () => {
  for (const fixture of goldmaster.fixtures) {
    it(`${fixture.id} — engine node is compared against SE mean and true node`, () => {
      const chart = runEngine(fixture);
      const actual = chart.placements.find((p) => p.key === "north_node")!;
      const seTrue = fixture.placements.find((p) => p.key === "true_node")!;
      // The engine's osculating node should be close to the SE TRUE node
      // (both are instantaneous); the documented tolerance is 1.5° because
      // osculating vs SE's true-node treatment differ slightly.
      degreesEqual(actual.longitude, seTrue.longitude, 1.5);
      // And it must never be near the SE MEAN node by coincidence of sign.
      expect(actual.sign).toBe(seTrue.signName);
    });
  }
});

describe("gold-master: nodeMode conventions (Swiss Ephemeris reference)", () => {
  function runEngineWithMode(fixture: GoldFixture, nodeMode: NodeMode) {
    return createChartProvider().calculate({
      utc: new Date(fixture.utcIso),
      latitude: fixture.lat,
      longitude: fixture.lon,
      timeKnown: fixture.timeKnown,
      nodeMode,
    });
  }

  it("mean mode matches SE mean node within 0.05°", () => {
    for (const fixture of goldmaster.fixtures) {
      const utc = new Date(fixture.utcIso);
      const mean = meanNodeLongitude(utc, 60);
      const seMean = fixture.placements.find((p) => p.key === "mean_node")!.longitude;
      degreesEqual(mean, seMean, 0.05);
    }
  });

  it("defaults to the osculating node and never labels it 'True node'", () => {
    const fixture = goldmaster.fixtures[0];
    const chart = runEngine(fixture);
    expect(chart.ephemerisConfig.northNodeConvention).toMatch(/Osculating/i);
    expect(chart.ephemerisConfig.northNodeConvention).not.toMatch(/^True node/i);
  });

  it("every displayed convention name matches the algorithm actually executed", () => {
    for (const fixture of goldmaster.fixtures) {
      const utc = new Date(fixture.utcIso);

      const osc = runEngineWithMode(fixture, "osculating");
      expect(osc.ephemerisConfig.northNodeConvention).toBe(NODE_MODE_LABELS.osculating);
      const oscNode = osc.placements.find((p) => p.key === "north_node")!;
      expect(oscNode.longitude).toBeCloseTo(northNodeLongitude(utc), 6);

      const mean = runEngineWithMode(fixture, "mean");
      expect(mean.ephemerisConfig.northNodeConvention).toBe(NODE_MODE_LABELS.mean);
      const meanNode = mean.placements.find((p) => p.key === "north_node")!;
      expect(meanNode.longitude).toBeCloseTo(
        meanNodeLongitude(utc, deltaT(utc.getUTCFullYear())),
        9
      );
    }
  });

  it("documents that osculating differs from SE true node enough to change the Sabian degree", () => {
    // In the committed fixture set, the osculating node and the SE true node
    // land in different Sabian degrees for a known subset of charts. Count that
    // subset so the disclosure stays accurate and auditable.
    let sabianDegreeDiffers = 0;
    for (const fixture of goldmaster.fixtures) {
      const utc = new Date(fixture.utcIso);
      const oscLon = northNodeLongitude(utc);
      const seTrue = fixture.placements.find((p) => p.key === "true_node")!;
      const oscSabian = Math.floor(oscLon % 30);
      const seSabian = Math.floor(seTrue.longitude % 30);
      if (oscSabian !== seSabian) sabianDegreeDiffers += 1;
    }
    // The disclosed figure is 4 of 14 fixtures.
    expect(goldmaster.fixtures.length).toBe(14);
    expect(sabianDegreeDiffers).toBe(4);
  });
});

describe("gold-master: Ascendant and Midheaven (Swiss Ephemeris reference)", () => {
  for (const fixture of goldmaster.fixtures.filter((f) => f.timeKnown)) {
    it(`${fixture.id} — Asc/MC match SE within 0.10°`, () => {
      const chart = runEngine(fixture);
      const asc = chart.placements.find((p) => p.key === "ascendant")!;
      const mc = chart.placements.find((p) => p.key === "midheaven")!;
      degreesEqual(asc.longitude, fixture.ascmc!.ascendant, 0.1);
      degreesEqual(mc.longitude, fixture.ascmc!.mc, 0.1);
    });
  }
});

describe("gold-master: Placidus houses (Swiss Ephemeris reference)", () => {
  for (const fixture of goldmaster.fixtures.filter((f) => f.timeKnown)) {
    it(`${fixture.id} — all 12 cusps match SE within 0.50°`, () => {
      const chart = runEngine(fixture);
      const houses = chart.houses!;
      expect(houses).toHaveLength(12);
      for (let i = 1; i <= 12; i++) {
        const cusp = houses.find((c) => c.house === i)!;
        degreesEqual(cusp.longitude, fixture.houses![String(i)], 0.5);
      }
    });
  }
});

describe("gold-master: Sabian degree and global index (EXACT)", () => {
  for (const fixture of goldmaster.fixtures) {
    it(`${fixture.id} — sabian degree + global index are EXACT for every placement`, () => {
      const chart = runEngine(fixture);
      for (const ref of fixture.placements) {
        const actual = chart.placements.find((p) => p.key === ref.key);
        if (!actual) continue;
        // Exact sabian degree and global index (no tolerance).
        expect(actual.sabianDegree).toBe(ref.sabian.sabianDegree);
        expect(actual.globalIndex).toBe(ref.sabian.globalIndex);
        expect(actual.sign).toBe(SIGNS_TROPICAL[ref.sign]);
      }
    });
  }
});

describe("gold-master: unknown-time chart contains no Asc/MC/houses", () => {
  it("unknown-time-tokyo — no time-dependent placements", () => {
    const fixture = goldmaster.fixtures.find((f) => f.id === "unknown-time-tokyo")!;
    const chart = runEngine(fixture);
    const keys = chart.placements.map((p) => p.key);
    expect(keys).not.toContain("ascendant");
    expect(keys).not.toContain("midheaven");
    expect(chart.houses).toBeUndefined();
  });
});
