/**
 * Deterministic local place index — the demo PlaceSearchProvider dataset.
 *
 * Contains real cities with real coordinates and IANA time zones (so the
 * historical-offset machinery is exercised with correct data), including
 * duplicate city names across countries/states, historical aliases, small towns,
 * and standard test identities. No external geocoding service is required in
 * demo mode.
 */

import type { PlaceResult } from "@/lib/types";

export const PLACES: PlaceResult[] = [
  // --- European Capitals & Historic Places ---
  {
    id: "wadowice-pl",
    displayName: "Wadowice",
    region: "Lesser Poland",
    country: "Poland",
    latitude: 49.8833,
    longitude: 19.5,
    timezone: "Europe/Warsaw",
  },
  {
    id: "london-uk",
    displayName: "London",
    region: "England",
    country: "United Kingdom",
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: "Europe/London",
  },
  {
    id: "paris-fr",
    displayName: "Paris",
    region: "Île-de-France",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: "Europe/Paris",
  },
  {
    id: "valletta-mt",
    displayName: "Valletta",
    region: "Malta Island",
    country: "Malta",
    latitude: 35.8989,
    longitude: 14.5146,
    timezone: "Europe/Malta",
  },
  {
    id: "reykjavik-is",
    displayName: "Reykjavík",
    region: "Capital Region",
    country: "Iceland",
    latitude: 64.1466,
    longitude: -21.9426,
    timezone: "Atlantic/Reykjavik",
  },
  {
    id: "glastonbury-uk",
    displayName: "Glastonbury",
    region: "Somerset",
    country: "United Kingdom",
    latitude: 51.1464,
    longitude: -2.7188,
    timezone: "Europe/London",
  },
  {
    id: "reine-no",
    displayName: "Reine",
    region: "Nordland",
    country: "Norway",
    latitude: 67.9333,
    longitude: 13.0833,
    timezone: "Europe/Oslo",
  },

  // --- Duplicate Names (Different Countries / States) ---
  {
    id: "london-ca",
    displayName: "London",
    region: "Ontario",
    country: "Canada",
    latitude: 42.9849,
    longitude: -81.2453,
    timezone: "America/Toronto",
  },
  {
    id: "paris-us-tx",
    displayName: "Paris",
    region: "Texas",
    country: "United States",
    latitude: 33.6609,
    longitude: -95.5555,
    timezone: "America/Chicago",
  },
  {
    id: "cambridge-uk",
    displayName: "Cambridge",
    region: "Cambridgeshire",
    country: "United Kingdom",
    latitude: 52.2053,
    longitude: 0.1218,
    timezone: "Europe/London",
  },
  {
    id: "cambridge-us-ma",
    displayName: "Cambridge",
    region: "Massachusetts",
    country: "United States",
    latitude: 42.3736,
    longitude: -71.1097,
    timezone: "America/New_York",
  },
  {
    id: "san-jose-us-ca",
    displayName: "San Jose",
    region: "California",
    country: "United States",
    latitude: 37.3382,
    longitude: -121.8863,
    timezone: "America/Los_Angeles",
  },
  {
    id: "san-jose-cr",
    displayName: "San José",
    region: "San José Province",
    country: "Costa Rica",
    latitude: 9.9281,
    longitude: -84.0907,
    timezone: "America/Costa_Rica",
  },
  {
    id: "springfield-us-il",
    displayName: "Springfield",
    region: "Illinois",
    country: "United States",
    latitude: 39.7817,
    longitude: -89.6501,
    timezone: "America/Chicago",
  },
  {
    id: "springfield-us-ma",
    displayName: "Springfield",
    region: "Massachusetts",
    country: "United States",
    latitude: 42.1015,
    longitude: -72.5898,
    timezone: "America/New_York",
  },

  // --- Historical / Renamed Places ---
  {
    id: "saint-petersburg-ru",
    displayName: "Saint Petersburg",
    region: "Northwestern Federal District",
    country: "Russia",
    latitude: 59.9311,
    longitude: 30.3609,
    timezone: "Europe/Moscow",
  },
  {
    id: "mumbai-in",
    displayName: "Mumbai",
    region: "Maharashtra",
    country: "India",
    latitude: 19.076,
    longitude: 72.8777,
    timezone: "Asia/Kolkata",
  },
  {
    id: "ho-chi-minh-city-vn",
    displayName: "Ho Chi Minh City",
    region: "Southeast",
    country: "Vietnam",
    latitude: 10.8231,
    longitude: 106.6297,
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    id: "istanbul-tr",
    displayName: "Istanbul",
    region: "Marmara",
    country: "Turkey",
    latitude: 41.0082,
    longitude: 28.9784,
    timezone: "Europe/Istanbul",
  },

  // --- Americas ---
  {
    id: "newyork-us",
    displayName: "New York City",
    region: "New York",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
  },
  {
    id: "losangeles-us",
    displayName: "Los Angeles",
    region: "California",
    country: "United States",
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: "America/Los_Angeles",
  },
  {
    id: "santabarbara-us",
    displayName: "Santa Barbara",
    region: "California",
    country: "United States",
    latitude: 34.4208,
    longitude: -119.6982,
    timezone: "America/Los_Angeles",
  },
  {
    id: "sedona-us-az",
    displayName: "Sedona",
    region: "Arizona",
    country: "United States",
    latitude: 34.8697,
    longitude: -111.761,
    timezone: "America/Phoenix",
  },
  {
    id: "marfa-us-tx",
    displayName: "Marfa",
    region: "Texas",
    country: "United States",
    latitude: 30.3094,
    longitude: -104.0205,
    timezone: "America/Chicago",
  },
  {
    id: "havana-cu",
    displayName: "Havana",
    region: "La Habana",
    country: "Cuba",
    latitude: 23.1136,
    longitude: -82.3666,
    timezone: "America/Havana",
  },

  // --- Asia, Pacific, Africa ---
  {
    id: "tokyo-jp",
    displayName: "Tokyo",
    region: "Tokyo Metropolis",
    country: "Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: "Asia/Tokyo",
  },
  {
    id: "delhi-in",
    displayName: "New Delhi",
    region: "Delhi",
    country: "India",
    latitude: 28.6139,
    longitude: 77.209,
    timezone: "Asia/Kolkata",
  },
  {
    id: "sydney-au",
    displayName: "Sydney",
    region: "New South Wales",
    country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: "Australia/Sydney",
  },
  {
    id: "auckland-nz",
    displayName: "Auckland",
    region: "Auckland Region",
    country: "New Zealand",
    latitude: -36.8485,
    longitude: 174.7633,
    timezone: "Pacific/Auckland",
  },
  {
    id: "moscow-ru",
    displayName: "Moscow",
    region: "Moscow",
    country: "Russia",
    latitude: 55.7558,
    longitude: 37.6173,
    timezone: "Europe/Moscow",
  },
  {
    id: "cairo-eg",
    displayName: "Cairo",
    region: "Cairo Governorate",
    country: "Egypt",
    latitude: 30.0444,
    longitude: 31.2357,
    timezone: "Africa/Cairo",
  },

  // --- Fictional Test Identities ---
  {
    id: "testvale-fict",
    displayName: "Testvale",
    region: "Fictional County",
    country: "Fiction",
    latitude: 51.2,
    longitude: -0.5,
    timezone: "Europe/London",
  },
  {
    id: "fictionalia-fict",
    displayName: "Fictionalia",
    region: "Fictional County",
    country: "Fiction",
    latitude: 49.85,
    longitude: 19.5,
    timezone: "Europe/Warsaw",
  },
];

/** Build the searchable index once at module load. */
import { indexPlaces } from "@/lib/time/birthtime";

export const placeIndex = indexPlaces(PLACES);
